services:

  php:
    build: .
    container_name: novacraft_php
    volumes:
      - "${LOCAL_PATH}:/var/www/html"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: novacraft_nginx
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - "${LOCAL_PATH}:/var/www/html"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  postgres:
    image: postgres:17-alpine
    container_name: novacraft_postgres_db
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgtables:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: novacraft_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

volumes:
  pgtables:
